"use client";

import {
  Loader2,
  Plus,
  Image as ImageIcon,
  Coins,
  Calendar,
  MoreVertical,
  Eye,
  Edit,
  Trash2,
  ExternalLink,
} from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";
import { useEffect, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "~/components/ui/card";
import { Button } from "~/components/ui/button";
import { Badge } from "~/components/ui/badge";
import Link from "next/link";

interface NFT {
  id: string;
  name: string;
  description: string;
  imageUrl: string;
  tokenId: string;
  contractAddress: string;
  blockchain: string;
  status: "draft" | "minted" | "listed" | "sold";
  price?: number;
  createdAt: Date;
  updatedAt: Date;
}

export default function NFTPage() {
  const { user, loading } = useAuth();
  const [isLoading, setIsLoading] = useState(true);
  const [userNFTs, setUserNFTs] = useState<NFT[]>([]);

  // Mock data for demonstration
  useEffect(() => {
    const mockNFTs: NFT[] = [
      {
        id: "1",
        name: "AI Generated Landscape",
        description: "A beautiful landscape generated by AI",
        imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop",
        tokenId: "12345",
        contractAddress: "0x1234567890abcdef",
        blockchain: "Sui",
        status: "minted",
        price: 0.5,
        createdAt: new Date("2024-01-15"),
        updatedAt: new Date("2024-01-15"),
      },
      {
        id: "2",
        name: "Futuristic City",
        description: "A cyberpunk cityscape created with AI",
        imageUrl: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=400&h=300&fit=crop",
        tokenId: "67890",
        contractAddress: "0xabcdef1234567890",
        blockchain: "Sui",
        status: "listed",
        price: 1.2,
        createdAt: new Date("2024-01-20"),
        updatedAt: new Date("2024-01-22"),
      },
    ];

    setTimeout(() => {
      setUserNFTs(mockNFTs);
      setIsLoading(false);
    }, 1000);
  }, []);

  const getStatusColor = (status: string) => {
    switch (status) {
      case "draft":
        return "bg-gray-100 text-gray-800";
      case "minted":
        return "bg-blue-100 text-blue-800";
      case "listed":
        return "bg-green-100 text-green-800";
      case "sold":
        return "bg-purple-100 text-purple-800";
      default:
        return "bg-gray-100 text-gray-800";
    }
  };

  if (loading || isLoading) {
    return (
      <div className="flex h-full items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin" />
      </div>
    );
  }

  if (!user) {
    return (
      <div className="flex h-full items-center justify-center">
        <p>Please log in to view your NFTs</p>
      </div>
    );
  }

  return (
    <div className="space-y-6 p-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">My NFTs</h1>
          <p className="text-muted-foreground">
            Manage your NFT collection and marketplace listings
          </p>
        </div>
        <Button className="gap-2">
          <Plus className="h-4 w-4" />
          Create NFT
        </Button>
      </div>

      {userNFTs.length === 0 ? (
        <Card>
          <CardContent className="flex flex-col items-center justify-center py-12">
            <ImageIcon className="h-12 w-12 text-muted-foreground" />
            <h3 className="mt-4 text-lg font-semibold">No NFTs yet</h3>
            <p className="text-muted-foreground">
              Start by creating your first NFT from your generated images
            </p>
            <Button className="mt-4 gap-2">
              <Plus className="h-4 w-4" />
              Create Your First NFT
            </Button>
          </CardContent>
        </Card>
      ) : (
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          {userNFTs.map((nft) => (
            <Card key={nft.id} className="overflow-hidden">
              <div className="aspect-square overflow-hidden">
                <img
                  src={nft.imageUrl}
                  alt={nft.name}
                  className="h-full w-full object-cover transition-transform hover:scale-105"
                />
              </div>
              <CardHeader className="pb-3">
                <div className="flex items-start justify-between">
                  <div className="space-y-1">
                    <CardTitle className="text-lg">{nft.name}</CardTitle>
                    <p className="text-sm text-muted-foreground line-clamp-2">
                      {nft.description}
                    </p>
                  </div>
                  <Badge className={getStatusColor(nft.status)}>
                    {nft.status}
                  </Badge>
                </div>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="flex items-center justify-between text-sm">
                  <div className="flex items-center gap-1">
                    <Coins className="h-4 w-4" />
                    <span>{nft.price ? `${nft.price} SUI` : "Not listed"}</span>
                  </div>
                  <div className="flex items-center gap-1">
                    <Calendar className="h-4 w-4" />
                    <span>{nft.createdAt.toLocaleDateString()}</span>
                  </div>
                </div>

                <div className="flex items-center justify-between">
                  <div className="text-xs text-muted-foreground">
                    Token ID: {nft.tokenId}
                  </div>
                  <div className="flex gap-1">
                    <Button variant="ghost" size="sm">
                      <Eye className="h-4 w-4" />
                    </Button>
                    <Button variant="ghost" size="sm">
                      <Edit className="h-4 w-4" />
                    </Button>
                    <Button variant="ghost" size="sm">
                      <MoreVertical className="h-4 w-4" />
                    </Button>
                  </div>
                </div>

                {nft.status === "listed" && (
                  <Button className="w-full gap-2" variant="outline">
                    <ExternalLink className="h-4 w-4" />
                    View on Marketplace
                  </Button>
                )}
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      <Card>
        <CardHeader>
          <CardTitle>NFT Statistics</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid gap-4 md:grid-cols-4">
            <div className="text-center">
              <div className="text-2xl font-bold">{userNFTs.length}</div>
              <div className="text-sm text-muted-foreground">Total NFTs</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-bold">
                {userNFTs.filter((nft) => nft.status === "minted").length}
              </div>
              <div className="text-sm text-muted-foreground">Minted</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-bold">
                {userNFTs.filter((nft) => nft.status === "listed").length}
              </div>
              <div className="text-sm text-muted-foreground">Listed</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-bold">
                {userNFTs.filter((nft) => nft.status === "sold").length}
              </div>
              <div className="text-sm text-muted-foreground">Sold</div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}